//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XMLtoDB
{


using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class MERCHANT_SO_ENTRY_DETAILS {
    public int ID { get; set; }

    private string bRANCHField;
    
    private string rEPORT_TYPEField;
    
    private string gRAND_TOTAL_TRField;
    
    private string gRAND_TOTAL_ORDERSField;
    
    private G_CONTRACTS[] lIST_G_CONTRACTSField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BRANCH {
        get {
            return this.bRANCHField;
        }
        set {
            this.bRANCHField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string REPORT_TYPE {
        get {
            return this.rEPORT_TYPEField;
        }
        set {
            this.rEPORT_TYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GRAND_TOTAL_TR {
        get {
            return this.gRAND_TOTAL_TRField;
        }
        set {
            this.gRAND_TOTAL_TRField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GRAND_TOTAL_ORDERS {
        get {
            return this.gRAND_TOTAL_ORDERSField;
        }
        set {
            this.gRAND_TOTAL_ORDERSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("G_CONTRACTS", typeof(G_CONTRACTS), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public G_CONTRACTS[] LIST_G_CONTRACTS {
        get {
            return this.lIST_G_CONTRACTSField;
        }
        set {
            this.lIST_G_CONTRACTSField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class G_CONTRACTS {
    public int ID { get; set; }

    private string aCNT_CONTRACT_CURRField;
    
    private string aCC_SCHEMEField;
    
    private string sERV_PACK_NAMEField;
    
    private string sERV_PACKField;
    
    private string cONTRACT_ADD_INFOField;
    
    private string cONTRACT_NUMBERField;
    
    private string zIP_CODEField;
    
    private string cLIENT_NAMEField;
    
    private string cOMPANYField;
    
    private string aDDRESS_LINE_1Field;
    
    private string aDDRESS_LINE_2Field;
    
    private string aDDRESS_LINE_3Field;
    
    private string rEG_NUMBERField;
    
    private string rEG_DETAILSField;
    
    private string idField;
    
    private string lIST_G_FIN_CONTRACTField;
    
    private string lIST_G_MESSAGE_DATEField;
    
    private string n_ORDERSField;
    
    private string n_TRField;
    
    private string sTMTDATETOField;
    
    private string sTMTDATEFROMField;
    
    private G_ORDER_TYPE[] lIST_G_ORDER_TYPEField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ACNT_CONTRACT_CURR {
        get {
            return this.aCNT_CONTRACT_CURRField;
        }
        set {
            this.aCNT_CONTRACT_CURRField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ACC_SCHEME {
        get {
            return this.aCC_SCHEMEField;
        }
        set {
            this.aCC_SCHEMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SERV_PACK_NAME {
        get {
            return this.sERV_PACK_NAMEField;
        }
        set {
            this.sERV_PACK_NAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SERV_PACK {
        get {
            return this.sERV_PACKField;
        }
        set {
            this.sERV_PACKField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CONTRACT_ADD_INFO {
        get {
            return this.cONTRACT_ADD_INFOField;
        }
        set {
            this.cONTRACT_ADD_INFOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CONTRACT_NUMBER {
        get {
            return this.cONTRACT_NUMBERField;
        }
        set {
            this.cONTRACT_NUMBERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ZIP_CODE {
        get {
            return this.zIP_CODEField;
        }
        set {
            this.zIP_CODEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CLIENT_NAME {
        get {
            return this.cLIENT_NAMEField;
        }
        set {
            this.cLIENT_NAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string COMPANY {
        get {
            return this.cOMPANYField;
        }
        set {
            this.cOMPANYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ADDRESS_LINE_1 {
        get {
            return this.aDDRESS_LINE_1Field;
        }
        set {
            this.aDDRESS_LINE_1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ADDRESS_LINE_2 {
        get {
            return this.aDDRESS_LINE_2Field;
        }
        set {
            this.aDDRESS_LINE_2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ADDRESS_LINE_3 {
        get {
            return this.aDDRESS_LINE_3Field;
        }
        set {
            this.aDDRESS_LINE_3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string REG_NUMBER {
        get {
            return this.rEG_NUMBERField;
        }
        set {
            this.rEG_NUMBERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string REG_DETAILS {
        get {
            return this.rEG_DETAILSField;
        }
        set {
            this.rEG_DETAILSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CONTRACTS_ID
        {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LIST_G_FIN_CONTRACT {
        get {
            return this.lIST_G_FIN_CONTRACTField;
        }
        set {
            this.lIST_G_FIN_CONTRACTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LIST_G_MESSAGE_DATE {
        get {
            return this.lIST_G_MESSAGE_DATEField;
        }
        set {
            this.lIST_G_MESSAGE_DATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string N_ORDERS {
        get {
            return this.n_ORDERSField;
        }
        set {
            this.n_ORDERSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string N_TR {
        get {
            return this.n_TRField;
        }
        set {
            this.n_TRField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string STMTDATETO {
        get {
            return this.sTMTDATETOField;
        }
        set {
            this.sTMTDATETOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string STMTDATEFROM {
        get {
            return this.sTMTDATEFROMField;
        }
        set {
            this.sTMTDATEFROMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("G_ORDER_TYPE", typeof(G_ORDER_TYPE), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public G_ORDER_TYPE[] LIST_G_ORDER_TYPE {
        get {
            return this.lIST_G_ORDER_TYPEField;
        }
        set {
            this.lIST_G_ORDER_TYPEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class G_ORDER_TYPE {
    public int ID { get; set; }

    private string oRDER_TYPEField;
    
    private string cONTRACT_IDField;
    
    private string n_ORDERS_PER_ORDER_TYPEField;
    
    private string n_TR_PER_ORDER_TYPEField;
    
    private G_ORDER[] lIST_G_ORDERField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ORDER_TYPE {
        get {
            return this.oRDER_TYPEField;
        }
        set {
            this.oRDER_TYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CONTRACT_ID {
        get {
            return this.cONTRACT_IDField;
        }
        set {
            this.cONTRACT_IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string N_ORDERS_PER_ORDER_TYPE {
        get {
            return this.n_ORDERS_PER_ORDER_TYPEField;
        }
        set {
            this.n_ORDERS_PER_ORDER_TYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string N_TR_PER_ORDER_TYPE {
        get {
            return this.n_TR_PER_ORDER_TYPEField;
        }
        set {
            this.n_TR_PER_ORDER_TYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("G_ORDER", typeof(G_ORDER), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public G_ORDER[] LIST_G_ORDER {
        get {
            return this.lIST_G_ORDERField;
        }
        set {
            this.lIST_G_ORDERField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class G_ORDER {
    public int ID { get; set; }
    public int G_ORDER_TYPE_ID { get; set; }

    private string oRDER_DOC_IDField;
    
    private string oRDER_DATEField;
    
    private string oRDER_AMNTField;
    
    private string oRDER_SOURCE_REG_NUMField;
    
    private string oRDER_CURRField;
    
    private string oRDER_CURR_EXPField;
    
    private string oRDER_TRANS_DETAILSField;
    
    private string s_ORDER_AMNT_PER_ORDERField;
    
    private string s_ORDER_FEE_AMOUNT_PER_ORDERField;
    
    private G_DEVICE[] lIST_G_DEVICEField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ORDER_DOC_ID {
        get {
            return this.oRDER_DOC_IDField;
        }
        set {
            this.oRDER_DOC_IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ORDER_DATE {
        get {
            return this.oRDER_DATEField;
        }
        set {
            this.oRDER_DATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ORDER_AMNT {
        get {
            return this.oRDER_AMNTField;
        }
        set {
            this.oRDER_AMNTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ORDER_SOURCE_REG_NUM {
        get {
            return this.oRDER_SOURCE_REG_NUMField;
        }
        set {
            this.oRDER_SOURCE_REG_NUMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ORDER_CURR {
        get {
            return this.oRDER_CURRField;
        }
        set {
            this.oRDER_CURRField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ORDER_CURR_EXP {
        get {
            return this.oRDER_CURR_EXPField;
        }
        set {
            this.oRDER_CURR_EXPField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ORDER_TRANS_DETAILS {
        get {
            return this.oRDER_TRANS_DETAILSField;
        }
        set {
            this.oRDER_TRANS_DETAILSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string S_ORDER_AMNT_PER_ORDER {
        get {
            return this.s_ORDER_AMNT_PER_ORDERField;
        }
        set {
            this.s_ORDER_AMNT_PER_ORDERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string S_ORDER_FEE_AMOUNT_PER_ORDER {
        get {
            return this.s_ORDER_FEE_AMOUNT_PER_ORDERField;
        }
        set {
            this.s_ORDER_FEE_AMOUNT_PER_ORDERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("G_DEVICE", typeof(G_DEVICE), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public G_DEVICE[] LIST_G_DEVICE {
        get {
            return this.lIST_G_DEVICEField;
        }
        set {
            this.lIST_G_DEVICEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class G_DEVICE {
    public int ID { get; set; }
    public int ORDER_ID { get; set; }

    private string dEVICE_NUMBERField;
    
    private string dEVICE_ADD_INFOField;
    
    private string s_ORDER_AMNT_PER_DEVField;
    
    private string s_ORDER_FEE_PER_DEVField;
    
    private G_TRANS_GROUP[] lIST_G_TRANS_GROUPField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DEVICE_NUMBER {
        get {
            return this.dEVICE_NUMBERField;
        }
        set {
            this.dEVICE_NUMBERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DEVICE_ADD_INFO {
        get {
            return this.dEVICE_ADD_INFOField;
        }
        set {
            this.dEVICE_ADD_INFOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string S_ORDER_AMNT_PER_DEV {
        get {
            return this.s_ORDER_AMNT_PER_DEVField;
        }
        set {
            this.s_ORDER_AMNT_PER_DEVField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string S_ORDER_FEE_PER_DEV {
        get {
            return this.s_ORDER_FEE_PER_DEVField;
        }
        set {
            this.s_ORDER_FEE_PER_DEVField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("G_TRANS_GROUP", typeof(G_TRANS_GROUP), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public G_TRANS_GROUP[] LIST_G_TRANS_GROUP {
        get {
            return this.lIST_G_TRANS_GROUPField;
        }
        set {
            this.lIST_G_TRANS_GROUPField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class G_TRANS_GROUP {
    public int ID { get; set; }
    public int DEVICE_ID { get; set; }

    private string tRANS_GROUPField;
    
    private string s_ORDER_AMNT_PER_TR_GRField;
    
    private string s_ORDER_FEE_PER_TR_GRField;
    
    private G_POSTING_DATE[] lIST_G_POSTING_DATEField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TRANS_GROUP {
        get {
            return this.tRANS_GROUPField;
        }
        set {
            this.tRANS_GROUPField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string S_ORDER_AMNT_PER_TR_GR {
        get {
            return this.s_ORDER_AMNT_PER_TR_GRField;
        }
        set {
            this.s_ORDER_AMNT_PER_TR_GRField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string S_ORDER_FEE_PER_TR_GR {
        get {
            return this.s_ORDER_FEE_PER_TR_GRField;
        }
        set {
            this.s_ORDER_FEE_PER_TR_GRField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("G_POSTING_DATE", typeof(G_POSTING_DATE), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public G_POSTING_DATE[] LIST_G_POSTING_DATE {
        get {
            return this.lIST_G_POSTING_DATEField;
        }
        set {
            this.lIST_G_POSTING_DATEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class G_POSTING_DATE {

    public int ID { get; set; }
    public int G_TRANS_GROUP_ID { get; set; }

    private string pOSTING_DATEField;
    
    private G_TRANS_DETAILS[] lIST_G_TRANS_DETAILSField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string POSTING_DATE {
        get {
            return this.pOSTING_DATEField;
        }
        set {
            this.pOSTING_DATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("G_TRANS_DETAILS", typeof(G_TRANS_DETAILS), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public G_TRANS_DETAILS[] LIST_G_TRANS_DETAILS {
        get {
            return this.lIST_G_TRANS_DETAILSField;
        }
        set {
            this.lIST_G_TRANS_DETAILSField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class G_TRANS_DETAILS {
    public int ID { get; set; }
    public int G_POSTING_DATE_ID { get; set; }

    private string tRANS_DETAILSField;
    
    private string tR_DOC_IDField;
    
    private string tRANS_REQUEST_CATField;
    
    private string tRANS_AMNTField;
    
    private string tRANS_CURRField;
    
    private string tRANS_CURR_EXPField;
    
    private string tRANS_DATEField;
    
    private string aDD_TRANS_DETAILSField;
    
    private string sOURCE_NUMBERField;
    
    private string sOURCE_TYPEField;
    
    private string tRANS_CODEField;
    
    private string tARGET_NUMBERField;
    
    private string tARGET_TYPEField;
    
    private string aUTH_CODEField;
    
    private string rRNField;
    
    private string bRANDField;
    
    private string mERCHANT_IDField;
    
    private string tRANS_TIMEField;
    
    private G_ENTRY[] lIST_G_ENTRYField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TRANS_DETAILS {
        get {
            return this.tRANS_DETAILSField;
        }
        set {
            this.tRANS_DETAILSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TR_DOC_ID {
        get {
            return this.tR_DOC_IDField;
        }
        set {
            this.tR_DOC_IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TRANS_REQUEST_CAT {
        get {
            return this.tRANS_REQUEST_CATField;
        }
        set {
            this.tRANS_REQUEST_CATField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TRANS_AMNT {
        get {
            return this.tRANS_AMNTField;
        }
        set {
            this.tRANS_AMNTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TRANS_CURR {
        get {
            return this.tRANS_CURRField;
        }
        set {
            this.tRANS_CURRField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TRANS_CURR_EXP {
        get {
            return this.tRANS_CURR_EXPField;
        }
        set {
            this.tRANS_CURR_EXPField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TRANS_DATE {
        get {
            return this.tRANS_DATEField;
        }
        set {
            this.tRANS_DATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ADD_TRANS_DETAILS {
        get {
            return this.aDD_TRANS_DETAILSField;
        }
        set {
            this.aDD_TRANS_DETAILSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SOURCE_NUMBER {
        get {
            return this.sOURCE_NUMBERField;
        }
        set {
            this.sOURCE_NUMBERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SOURCE_TYPE {
        get {
            return this.sOURCE_TYPEField;
        }
        set {
            this.sOURCE_TYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TRANS_CODE {
        get {
            return this.tRANS_CODEField;
        }
        set {
            this.tRANS_CODEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TARGET_NUMBER {
        get {
            return this.tARGET_NUMBERField;
        }
        set {
            this.tARGET_NUMBERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TARGET_TYPE {
        get {
            return this.tARGET_TYPEField;
        }
        set {
            this.tARGET_TYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AUTH_CODE {
        get {
            return this.aUTH_CODEField;
        }
        set {
            this.aUTH_CODEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RRN {
        get {
            return this.rRNField;
        }
        set {
            this.rRNField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BRAND {
        get {
            return this.bRANDField;
        }
        set {
            this.bRANDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MERCHANT_ID {
        get {
            return this.mERCHANT_IDField;
        }
        set {
            this.mERCHANT_IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TRANS_TIME {
        get {
            return this.tRANS_TIMEField;
        }
        set {
            this.tRANS_TIMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("G_ENTRY", typeof(G_ENTRY), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public G_ENTRY[] LIST_G_ENTRY {
        get {
            return this.lIST_G_ENTRYField;
        }
        set {
            this.lIST_G_ENTRYField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class G_ENTRY {
    public int ID { get; set; }
    public int G_TRANS_DETAILS_ID { get; set; }

    private string eNTRY_DETAILSField;
    
    private string eNTRY_DESCRIPTIONField;
    
    private string eNTRY_CURR_EXPField;
    
    private string eNTRY_DIRECTIONField;
    
    private string eNTRY_AMOUNTField;
    
    private string eNTRY_CURRField;
    
    private string eNTRY_TYPEField;
    
    private string pAYM_AMOUNTField;
    
    private string pAYM_CURRField;
    
    private string pAYM_CURR_EXPField;
    
    private string iS_PART_OF_PAYMENTField;
    
    private string eNTRY_IDField;
    
    private string oRDER_BASE_AMOUNTField;
    
    private string oRDER_FEE_AMOUNTField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ENTRY_DETAILS {
        get {
            return this.eNTRY_DETAILSField;
        }
        set {
            this.eNTRY_DETAILSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ENTRY_DESCRIPTION {
        get {
            return this.eNTRY_DESCRIPTIONField;
        }
        set {
            this.eNTRY_DESCRIPTIONField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ENTRY_CURR_EXP {
        get {
            return this.eNTRY_CURR_EXPField;
        }
        set {
            this.eNTRY_CURR_EXPField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ENTRY_DIRECTION {
        get {
            return this.eNTRY_DIRECTIONField;
        }
        set {
            this.eNTRY_DIRECTIONField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ENTRY_AMOUNT {
        get {
            return this.eNTRY_AMOUNTField;
        }
        set {
            this.eNTRY_AMOUNTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ENTRY_CURR {
        get {
            return this.eNTRY_CURRField;
        }
        set {
            this.eNTRY_CURRField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ENTRY_TYPE {
        get {
            return this.eNTRY_TYPEField;
        }
        set {
            this.eNTRY_TYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PAYM_AMOUNT {
        get {
            return this.pAYM_AMOUNTField;
        }
        set {
            this.pAYM_AMOUNTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PAYM_CURR {
        get {
            return this.pAYM_CURRField;
        }
        set {
            this.pAYM_CURRField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PAYM_CURR_EXP {
        get {
            return this.pAYM_CURR_EXPField;
        }
        set {
            this.pAYM_CURR_EXPField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IS_PART_OF_PAYMENT {
        get {
            return this.iS_PART_OF_PAYMENTField;
        }
        set {
            this.iS_PART_OF_PAYMENTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ENTRY_ID {
        get {
            return this.eNTRY_IDField;
        }
        set {
            this.eNTRY_IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ORDER_BASE_AMOUNT {
        get {
            return this.oRDER_BASE_AMOUNTField;
        }
        set {
            this.oRDER_BASE_AMOUNTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ORDER_FEE_AMOUNT {
        get {
            return this.oRDER_FEE_AMOUNTField;
        }
        set {
            this.oRDER_FEE_AMOUNTField = value;
        }
    }
}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
//public partial class NewDataSet {
//    public int ID { get; set; }

//    private MERCHANT_SO_ENTRY_DETAILS[] itemsField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("MERCHANT_SO_ENTRY_DETAILS")]
//    public MERCHANT_SO_ENTRY_DETAILS[] Items {
//        get {
//            return this.itemsField;
//        }
//        set {
//            this.itemsField = value;
//        }
//    }
//}
}